#Deploy configuration for Render.com
services:
  - type: web
    name: web2-22810209
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /indexa.php
